url: "https://mediocre.pl"
name: "Mediocre Game Studios"
description: "We're making sort of good games."

lang: pl_PL
language: pl
encoding: utf-8
timezone: Europe/Warsaw

future: false
unpublished: false
permalink: /blog/:title

links:
  local:
    - name: About Us
      href: /about-us
    - name: Feed
      href: /feed.xml

  external:
    - name: GitHub
      href: https://github.com/mediocre-game-studios
    - name: Twitter
      href: https://twitter.com/mediocre-game-studios

pages_dir: pages
posts_dir: posts
assets_dir: files
layouts_dir: layouts
includes_dir: includes

include:
  - files

exclude:
  - layouts
  - includes
  - README.md
  - CNAME

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

highlighter: rouge

scss:
  style: compressed
