url: "https://mediocre.pl"
name: "Mediocre Game Studios"
description: "We're making sort of good games."

lang: pl_PL
language: pl
encoding: utf-8
timezone: Europe/Warsaw

future: false
unpublished: false
permalink: /blog/:title

links:
  local:
    - name: about
      href: /about
    - name: feed
      href: /feed.xml

  external:
    - name: github
      href: https://github.com/mediocre-game-studios
    - name: twitter
      href: https://twitter.com/mediocre-game-studios

pages_dir: pages
posts_dir: posts
assets_dir: files
layouts_dir: layouts
includes_dir: includes

include:
  - pages
  - posts
  - files

exclude:
  - CNAME
  - README.md
  - includes

plugins:
  - jekyll-feed
  - jekyll-sitemap
# - jekyll-seo-tag

markdown: kramdown

scss:
  style: compressed

# compress.html by Jonathan Volebregt
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
    blanklines: false
    profile: false
    startings: [html, head, body]
