url: "https://mediocre.pl"
name: "MEDIOCRE SOFTWARE STUDIOS"
description: "We're making sort of good software (and games!)"

lang: pl_PL
language: pl
encoding: utf-8
timezone: Europe/Warsaw

future: false
unpublished: false
permalink: /blog/:title

links:
  - name: About Us
    href: /about-us
  - name: GitHub
    href: https://github.com/mediocre-software-studios
  - name: Twitter
    href: https://twitter.com/mediocre-software-studios

pages_dir: pages
posts_dir: posts
assets_dir: files
layouts_dir: layouts
includes_dir: includes

include:
  - files

exclude:
  - layouts
  - includes
  - README.md
  - CNAME

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

highlighter: rouge

scss:
  style: compressed
